### ISSUE TITLE
Some tiles missing when camera is moving

### ISSUE THREAD

**Issue by corybarr** [CesiumGS/cesium-omniverse#325] opened 2023-06-08 15:44 UTC
Some tiles in Cesium World Terrain are missing when the camera is moving. As soon as camera motion is stopped, the tiles appear.

https://github.com/CesiumGS/cesium-omniverse/assets/1040194/6b3f2f5b-f308-4e0c-8c70-29b4791f34de

**Comment by lilleyse** [comment] 2023-06-08 16:16
Duplicate of https://github.com/CesiumGS/cesium-omniverse/issues/255. This will be fixed in Kit 105 without any changes on our end.

**Closed by lilleyse** 2023-06-08 16:16 UTC
